name: libre_doc_converter
description: A Dart/Flutter library for converting documents using libreoffice.
version: 0.1.0
repository: https://github.com/jotaonti/libre_doc_converter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
